# Web server settings.
server:
  # Root URI for REST resources
  rootPath: '/api/*'

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  # the username
  user: user
  # the password
  password: pass
  # the JDBC URL
  url: jdbc:h2:~/test

